;Body Material
[Skin_Body]
Count = 2
1_Traditional = $/Substance/G6_Body.ccTexture
2_PBR_Basic = $/Substance/PBR_Basic/CC_Body.ccTexture

[Skin_Head]
Count = 2
1_Traditional = $/Substance/G6_Head.ccTexture
2_PBR_Basic = $/Substance/PBR_Basic/CC_Head.ccTexture

[Eyelash]
Count = 2
1_Traditional = $/Substance/G6_Eyelashes.ccTexture
2_PBR_Basic = $/Substance/PBR_Basic/CC_Eyelashes.ccTexture

[Fingernail]
Count = 2
1_Traditional = $/Substance/G6_Fingernails.ccTexture
2_PBR_Basic = $/Substance/PBR_Basic/CC_Fingernails.ccTexture

[Toenail]
Count = 2
1_Traditional = $/Substance/G6_Toenails.ccTexture
2_PBR_Basic = $/Substance/PBR_Basic/CC_Toenails.ccTexture

[Tongue]
Count = 2
1_Traditional = $/Substance/G6_Tongue.ccTexture
2_PBR_Basic = $/Substance/PBR_Basic/CC_Tongue.ccTexture

;Eyes Material
[Eye]
Count = 2
1_Traditional = $/Substance/G6_Eyes.ccTexture
2_PBR_Basic = $/Substance/PBR_Basic/CC_Eyes.ccTexture

[Cornea]
Count = 2
1_Traditional = $/Substance/G6_Eyes.ccTexture
2_PBR_Basic = $/Substance/PBR_Basic/CC_Eyes.ccTexture

;Teeth Material
[Upper_Teeth]
Count = 2
1_Traditional = $/Substance/G6_UpperTeeth.ccTexture
2_PBR_Basic = $/Substance/PBR_Basic/CC_UpperTeeth.ccTexture

[Lower_Teeth]
Count = 2
1_Traditional = $/Substance/G6_LowerTeeth.ccTexture
2_PBR_Basic = $/Substance/PBR_Basic/CC_LowerTeeth.ccTexture

;Hair
[Hair]
Count = 2
1_Traditional = $/Substance/G6_Hair.ccTexture
2_PBR_Basic = $/Substance/PBR_Basic/CC_Hair.ccTexture

[Cloth]
Count = 4
1_Traditional = $/Substance/G6_Cloth.ccTexture
2_PBR_V1_3MAT = $/Substance/PBR_V1/CC_PBR_Cloth_V1_3MAT.ccTexture
3_PBR_V1_5MAT = $/Substance/PBR_V1/CC_PBR_Cloth_V1_5MAT.ccTexture
4_PBR_V1_7MAT = $/Substance/PBR_V1/CC_PBR_Cloth_V1_7MAT.ccTexture

[Accessory]
Count = 4
1_Traditional = $/Substance/G6_Cloth.ccTexture
2_PBR_V1_3MAT = $/Substance/PBR_V1/CC_PBR_Cloth_V1_3MAT.ccTexture
3_PBR_V1_5MAT = $/Substance/PBR_V1/CC_PBR_Cloth_V1_5MAT.ccTexture
4_PBR_V1_7MAT = $/Substance/PBR_V1/CC_PBR_Cloth_V1_7MAT.ccTexture

[LegacySubstance]
File1  = $/Substance/G6_Body.ccTexture
File2  = $/Substance/G6_Head.ccTexture
File3  = $/Substance/G6_Eyelashes.ccTexture
File4  = $/Substance/G6_Fingernails.ccTexture
File5  = $/Substance/G6_Toenails.ccTexture
File6  = $/Substance/G6_Tongue.ccTexture
File7  = $/Substance/G6_Eyes.ccTexture
File8  = $/Substance/G6_Eyes.ccTexture
File9  = $/Substance/G6_UpperTeeth.ccTexture
File10 = $/Substance/G6_LowerTeeth.ccTexture
File11 = $/Substance/G6_Hair.ccTexture
File12 = $/Substance/G6_Cloth.ccTexture

[PbrSubstance]
File1  = $/Substance/PBR_Basic/CC_Body.ccTexture
File2  = $/Substance/PBR_Basic/CC_Head.ccTexture
File3  = $/Substance/PBR_Basic/CC_Eyelashes.ccTexture
File4  = $/Substance/PBR_Basic/CC_Fingernails.ccTexture
File5  = $/Substance/PBR_Basic/CC_Toenails.ccTexture
File6  = $/Substance/PBR_Basic/CC_Tongue.ccTexture
File7  = $/Substance/PBR_Basic/CC_Eyes.ccTexture
File8  = $/Substance/PBR_Basic/CC_Eyes.ccTexture
File9  = $/Substance/PBR_Basic/CC_UpperTeeth.ccTexture
File10 = $/Substance/PBR_Basic/CC_LowerTeeth.ccTexture
File11 = $/Substance/PBR_Basic/CC_Hair.ccTexture
File12 = $/Substance/G6_PBR_Cloth.ccTexture
File13 = $/Substance/PBR_V1/CC_PBR_Cloth_V1_3MAT.ccTexture
File14 = $/Substance/PBR_V1/CC_PBR_Cloth_V1_5MAT.ccTexture
File15 = $/Substance/PBR_V1/CC_PBR_Cloth_V1_7MAT.ccTexture